### ISSUE TITLE
Enabling GPU Support: CUDA error 222

### ISSUE THREAD

**Issue by PanZWarzywniaka** [imartinez/privateGPT#1304]
Hi,

When I try to run
`$env:CMAKE_ARGS='-DLLAMA_CUBLAS=on'; poetry run pip install --force-reinstall --no-cache-dir llama-cpp-python
`
Model loads and sever starts but when I enter first prompt I get the following error

`CUDA error 222 at /tmp/pip-install-zhyjy1q2/llama-cpp-python_c40ab0ad2da54363b5e19e835a1b6768/vendor/llama.cpp/ggml-cuda.cu:6951: the provided PTX was compiled with an unsupported toolchain.
current device: 0
`

My steps so far:

1. Cloned repo
2. Installed `make`
3. `poetry install --with ui`
4. Installed cuda 
5. Added cuda binaries to path so `nvcc` and `nvidia-smi` are accessable.
6. Updated nvidia drivers,

My OS: Manjaro Linux
Nvidia Drivers 535.129.03   
CUDA Version: 12.2

Using privateGPT on CPU work fine though.

Thank you for any help
Olek

**Comment by gianniacquisto** [comment]
you could try this:
`CUDACXX=/usr/local/cuda-12/bin/nvcc CMAKE_ARGS="-DLLAMA_CUBLAS=on -DCMAKE_CUDA_ARCHITECTURES=native" FORCE_CMAKE=1 pip install llama-cpp-python --no-cache-dir --force-reinstall --upgrade`

it worked for me

**Comment by Will-Bethard** [comment]
I used the last part of @gianniacquisto  reply : 

`pip install llama-cpp-python --no-cache-dir --force-reinstall --upgrade`

and this worked on Ubuntu 22.  The full command gave me an error.

**Comment by chutianshu1981** [comment]
same issue on win 11 .
server can run  :

poetry run python -m private_gpt
11:43:29.492 [INFO    ] private_gpt.settings.settings_loader - Starting application with profiles=['default']
11:43:31.320 [INFO    ] private_gpt.components.llm.llm_component - Initializing the LLM in mode=local
ggml_init_cublas: GGML_CUDA_FORCE_MMQ:   no
ggml_init_cublas: CUDA_USE_TENSOR_CORES: yes
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 4070, compute capability 8.9
  llama_model_loader: loaded meta data with 20 key-value pairs and 291 tensors from E:\_XiongWorkSpace\AIWorkSpace\privateGPT\models\mistral-7b-instruct-v0.1.Q4_K_M.gguf (version GGUF V2)
 ...................
 llm_load_vocab: special tokens definition check successful ( 259/32000 ).
 llm_load_tensors: using CUDA for GPU acceleration
llm_load_tensors: mem required  =   70.42 MiB
llm_load_tensors: offloading 32 repeating layers to GPU
llm_load_tensors: offloading non-repeating layers to GPU
llm_load_tensors: offloaded 35/35 layers to GPU
llm_load_tensors: VRAM used: 4095.05 MiB
....................
llama_new_context_with_model: total VRAM used: 4857.93 MiB (model: 4095.05 MiB, context: 762.87 MiB)
AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 0 | VSX = 0 |
11:43:34.274 [INFO    ] private_gpt.components.embedding.embedding_component - Initializing the embedding model in mode=local
11:43:38.054 [INFO    ] llama_index.indices.loading - Loading all indices.
11:43:38.164 [INFO    ]         private_gpt.ui.ui - Mounting the gradio UI, at path=/
11:43:38.211 [INFO    ]             uvicorn.error - Started server process [15796]
11:43:38.211 [INFO    ]             uvicorn.error - Waiting for application startup.
11:43:38.211 [INFO    ]             uvicorn.error - Application startup complete.
11:43:38.211 [INFO    ]             uvicorn.error - Uvicorn running on http://0.0.0.0:8001 (Press CTRL+C to quit)


but got the same error :

CUDA error 222 at C:\Users\jing\AppData\Local\Temp\pip-install-4nad2bq4\llama-cpp-python_35582f9ebf50458b9f020127afde2c1b\vendor\llama.cpp\ggml-cuda.cu:6959: the provided PTX was compiled with an unsupported toolchain.
current device: 0
